main: de.jaylawl.perplayerdripleaf.PerPlayerDripleaf
name: PerPlayerDripleaf
version: 1.0.0
author: jaylawl

api-version: "1.17"
load: STARTUP
depend: [ ]
softdepend: [ ]
loadbefore: [ ]

commands: { }

permissions: { }